[package]
name = "simple_bench"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version = "=0.11.11", default-features = false, features = ["rustls-tls"]}
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
