[package]
name = "simple_bench"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version = "0.12.5", default-features = false, features = ["http2", "charset", "rustls-tls"]}
tokio = "1.39.2"
